// Auto-generated by CalcDocs Formula Outline
#pragma once

// Formula: VEL = 6 * (MUL)
#define VEL                              (6 * (4))  // [V]

// Formula: VEL_MV = 5 * MUL
#define VEL_MV                           (20000)  // [mV]

// Formula: TEST_VEL = 5 * 6 V
#define TEST_VEL                         (30000)  // [mV]

// Constant: ADC_MAX [count]
#define ADC_MAX                          (4095)  // [count]

// Constant: R_PULLUP [ohm]
#define R_PULLUP                         (10000)  // [ohm]

// Formula: NTC_ADC_10K_25C = csv("ntc_10k_table.csv", "25", "temp_c", "resistance_ohm")
#define NTC_ADC_10K_25C                  (10000)

// Formula: NTC_ADC_10K_22C = -csv("ntc_10k_table.csv", "23.1", "temp_c", "resistance_ohm", "linear")
#define NTC_ADC_10K_22C                  (-11254)

// Formula: NTC_ADC_10K_22C_ABS = sin(-csv("ntc_10k_table.csv", "19.1", "temp_c", "resistance_ohm", "linear"))
#define NTC_ADC_10K_22C_ABS              (-0.953398608201182)

// Constant: TEST_CURR [mA]
#define TEST_CURR                        (100)  // [mA]

// WARNING: TEST_VOLT ha unità embedded ma manca il campo value:
// Formula originale: NTC_R * 200 mA

// Formula: NTC_ADC = ADC_MAX * NTC_R / (R_PULLUP + NTC_R)
#define NTC_ADC(NTC_R) (4095 * NTC_R / (10000 + NTC_R))  // [V]

