// Auto-generated by CalcDocs Formula Outline
#pragma once

// Formula: R = csv("table.csv", "24.9", "temp", "res", "linear")
#define R                                (10080)  // [degc]

// Constant: current [A]
#define CURRENT                          (2)  // [A]

// Constant: vin [V]
#define VIN                              (24)  // [V]

// Formula: power = current * vin
#define POWER(current, vin) (current * vin)  // [W]

// Formula: NTC_R_25 = csv("data/ntc_10k.csv", "25", "temp_c", "res_ohm")
#define NTC_R_25                         (10000)  // [degc]

