import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import type { OutlineFormula } from '../formulaOutline/formulaParser';
import { expandExpression } from '../core/expression';
import type { CalcDocsState } from '../core/state';

// ── Costanti ─────────────────────────────────────────────────────────────────

const RESERVED = new Set([
  'sin','cos','tan','asin','acos','atan','atan2','sqrt','abs','min','max','pow',
  'floor','ceil','round','log','log10','exp',
  'pi','e','deg2rad','rad2deg','csv','table','lookup',
  'uint8_t','uint16_t','uint32_t','int8_t','int16_t','int32_t','float','double','bool'
]);

const UNITS = new Set([
  'ma','a','mv','v','ohm','kohm','mohm','ms','us','s','m','km',
  'g','kg','deg','c','f','k','bar','pa','hpa','ppm','ppb'
]);

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Rileva unità di misura embedded nell'espressione (es. "200 mA", "5 V").
 * Questi non sono espressioni C valide: va usato il campo `value` come fallback.
 */
function hasEmbeddedUnit(expr: string): boolean {
  const unitList = [...UNITS].join('|');
  return new RegExp(`\\d+(\\.\\d+)?\\s+(${unitList})\\b`, 'i').test(expr);
}

/**
 * Estrae gli identificatori sconosciuti dall'espressione già espansa,
 * escludendo: funzioni riservate, valori noti, unità di misura post-numero.
 */
function extractUnknownParams(
  expr: string,
  knownValues: Map<string, string>
): string[] {
  const tokens: string[] = [];
  let inString = false;
  let currentToken = '';
  let prevNonSpace = '';

  const flush = (nextChar: string) => {
    if (currentToken) {
      // Salta token che è un'unità di misura subito dopo un numero (es. "10mA")
      const isUnit = /[0-9.]/.test(prevNonSpace) && UNITS.has(currentToken.toLowerCase());
      if (!isUnit) tokens.push(currentToken);
      currentToken = '';
    }
    if (nextChar !== ' ' && nextChar !== '\t' && nextChar !== '\0') {
      prevNonSpace = nextChar;
    }
  };

  for (let i = 0; i <= expr.length; i++) {
    const c = i < expr.length ? expr[i] : '\0';

    if (c === '"' || c === "'") {
      flush(c);
      inString = !inString;
      continue;
    }
    if (inString) { prevNonSpace = c; continue; }

    if (/[A-Za-z_]/.test(c)) {
      currentToken += c;
    } else if (/[0-9]/.test(c) && currentToken) {
      // Cifra all'interno di un identificatore (es. "var1")
      currentToken += c;
    } else {
      flush(c);
      // Aggiorna prevNonSpace per cifre standalone (per rilevare "200 mA")
      if (/[0-9.]/.test(c)) prevNonSpace = c;
    }
  }

  return [...new Set(tokens)].filter(t =>
    !RESERVED.has(t.toLowerCase()) &&
    !knownValues.has(t) &&
    !knownValues.has(t.toLowerCase()) &&
    !knownValues.has(t.toUpperCase())
  );
}

// ── Generatore ────────────────────────────────────────────────────────────────

export async function generateFormulaHeader(
  formulas: OutlineFormula[],
  outputPath: string,
  state: CalcDocsState
) {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
  if (!workspaceRoot) return;

  const headerPath = path.join(workspaceRoot, outputPath);
  let content = '// Auto-generated by CalcDocs Formula Outline\n#pragma once\n\n';

  // ── Valori noti: SOLO simboli risolti dall'analisi C/C++ ─────────────────
  //
  // I campi `value` dello yaml sono valori di esempio/documentazione,
  // NON sostituti a compile-time. Solo state.symbolValues fornisce sostituzioni.
  // Questo garantisce che identificatori definiti solo in yaml (es. NTC_R)
  // rimangano come parametri della macro invece di essere espansi.
  const knownValues = new Map<string, string>();
  state.symbolValues.forEach((val: any, name: string) => {
    if (val !== undefined && val !== null) {
      knownValues.set(name, String(val));
    }
  });

  for (const f of formulas) {
    const idUpper = f.id.toUpperCase();
    const unitComment = f.unit ? `  // [${f.unit}]` : '';

    // ── Caso A: costante pura (nessuna formula) ──────────────────────────
    if (!f.expr) {
      if (f.value !== undefined) {
        content += `// Constant: ${f.id}${f.unit ? ` [${f.unit}]` : ''}\n`;
        content += `#define ${idUpper.padEnd(32)} (${f.value})${unitComment}\n\n`;
      }
      continue;
    }

    // ── Caso B: formula con csv() → valore numerico precalcolato ─────────
    //
    // csv() non è esprimibile come macro C; si usa il valore già risolto.
    if (/\bcsv\s*\(/.test(f.expr)) {
      if (f.value !== undefined) {
        content += `// Formula: ${f.id} = ${f.expr}\n`;
        content += `#define ${idUpper.padEnd(32)} (${f.value})${unitComment}\n\n`;
      } else {
        content += `// WARNING: ${f.id} usa csv() ma manca il campo value:\n`;
        content += `// #define ${idUpper}  ???\n\n`;
      }
      continue;
    }

    // ── Caso C: formula con unità embedded (es. "200 mA") → usa value ────
    //
    // Espressioni con unità fisiche integrate non sono C valide.
    if (hasEmbeddedUnit(f.expr)) {
      if (f.value !== undefined) {
        content += `// Formula: ${f.id} = ${f.expr}\n`;
        content += `#define ${idUpper.padEnd(32)} (${f.value})${unitComment}\n\n`;
      } else {
        content += `// WARNING: ${f.id} ha unità embedded ma manca il campo value:\n`;
        content += `// Formula originale: ${f.expr}\n\n`;
      }
      continue;
    }

    // ── Caso D: espansione con simboli C noti ────────────────────────────
    const expanded = expandExpression(f.expr, knownValues, new Map(), new Map(), new Map());
    const unknownParams = extractUnknownParams(expanded, knownValues);

    if (unknownParams.length === 0) {
      // D1: completamente risolta → usa yaml `value` se disponibile (più preciso),
      //     altrimenti usa l'espressione espansa.
      const resolved = f.value !== undefined ? f.value : expanded;
      content += `// Formula: ${f.id} = ${f.expr}\n`;
      content += `#define ${idUpper.padEnd(32)} (${resolved})${unitComment}\n\n`;
    } else {
      // D2: macro parametrica con identificatori rimasti sconosciuti
      const params = unknownParams.join(', ');
      content += `// Formula: ${f.id} = ${f.expr}\n`;
      content += `#define ${idUpper}(${params}) (${expanded})${unitComment}\n\n`;
    }
  }

  await fs.writeFile(headerPath, content);
  vscode.window.showInformationMessage(`Generated ${headerPath}`);
}